plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.project'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
//	Swagger UI를 사용하기 위한 의존성을 추가한다
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.3'
//	DTO와 엔티티 간 객체 매핑을 위한 MapStruct
	implementation 'org.mapstruct:mapstruct:1.6.3'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'com.oracle.database.jdbc:ojdbc11'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'
	//	Lombok 애노테이션 처리
	annotationProcessor 'org.projectlombok:lombok'
//	Lombok과 MapStruct의 애노테이션 처리 연동
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
//	DTO와 엔티티 간 객체 매핑을 위한 MapStruct
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
	// QueryDSL 의존성 추가(검색 필터기능 구현때)
	implementation 'com.querydsl:querydsl-jpa:5.1.0:jakarta'
	annotationProcessor 'com.querydsl:querydsl-apt:5.1.0:jakarta'
	annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
	annotationProcessor 'jakarta.persistence:jakarta.persistence-api'
	// json 데이터르 처리하기 위한 라이브러리
	implementation 'org.json:json:20250517'
	implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml'
	// API 서버 비동기 호출
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	// 외부 API 파싱 및 정보 추출
	implementation 'org.jsoup:jsoup:1.17.2'
	// 썸네일 의존성
	implementation 'net.coobird:thumbnailator:0.4.20'
}

tasks.named('test') {
	useJUnitPlatform()
}
