spring.application.name=articket

# datasource (oracle)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
spring.datasource.username=user
spring.datasource.password=password

# jpa setting
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.open-in-view=true

# OpenAPI 문서(/v3/api-docs) 제공기능 비활성화
springdoc.api-docs.enabled=false

# Swagger UI 화면 제공 기능 비활성화
springdoc.swagger-ui.enabled=false
# 스프링 시큐리티의 요청 처리 과정과 필터 체인의 동작을 자세히 확인하기 위해 로그 레벨을 설정한다.
logging.level.org.springframework.security.web=TRACE

# 공공데이터 포털 인증키
openapi.service-key = 본인 인증키

# 파일 업로드
# 파일 하나의 최대 업로드 크기
spring.servlet.multipart.max-file-size=5MB

# 한 번의 요청으로 전송할 수 있는 전체 데이터의 최대 크기
spring.servlet.multipart.max-request-size=15MB

# 업로드 파일 저장 경로
#com.spring.website.upload.path=upload